Exercise 1: Text Cleaning - Removing unwanted characters and normalizing text

Aim :
      To perform text cleaning by removing unwanted characters and normalizing text.

Pre-Lab Task:

1. Define Text Cleaning

Ans: Text Cleaning is the process of preparing raw text data by removing unwanted parts (like noise, symbols, or formatting) so that it becomes clean, consistent, and ready for analysis or modeling in NLP.

2. Write the method used to remove the following
    1. HTML tags
    2. URLs
    3. Email addresses
    4. Digits
    5. Extra spaces
    6. Uppercase letters (converted to lowercase)

1. HTML tags → Use BeautifulSoup library (soup.get_text()) or regex <.*?>

2. URLs → Regex pattern: https?://\S+

3. Email addresses → Regex pattern: \S+@\S+

4. Digits → Regex pattern: \d+

5. Extra spaces → Regex pattern: \s+ (replace with single space)

6. Uppercase letters (convert to lowercase) → Use Python string method: text.lower()

3. What is the purpose of regular expressions?

Ans: Regular Expressions (Regex) are used to search, match, and manipulate text patterns. They help in finding specific sequences (like emails, numbers, or symbols) and replacing or removing them efficiently.

4. Python Library to Remove HTML Tags?

Ans: The most commonly used library is BeautifulSoup
example or code:
from bs4 import BeautifulSoup
clean_text = BeautifulSoup(raw_html, "html.parser").get_text()

In [ ]:
from bs4 import BeautifulSoup
clean_text = BeautifulSoup(raw_html, "html.parser").get_text()

5. What is the difference between \d+ and \W+ in regular expressions?

Ans: \d+ → Matches one or more digits (0–9).
Example: "abc123" → matches 123

\W+ → Matches one or more non‑word characters (anything except letters, digits, and underscore).
Example: "hello!!!" → matches !!!

In- Lab Task
Tasks
1. Create a Python list containing the given text corpus.
2. Import the required libraries (re and BeautifulSoup).
3. Convert all text to lowercase.
4. Remove HTML tags.
5. Remove URLs.
6. Remove email addresses.
7. Remove digits.
8. Remove punctuation and special characters.
9. Remove extra white spaces.
10. Store the cleaned text in a new list named cleaned_corpus.
11. Display the original corpus and the cleaned corpus.
12. Compare the text before and after cleaning.

1. Create a Python list containing the given text corpus.

In [3]:
corpus = [
    "<p>Data Science is AMAZING!!! Visit https://datascience.com</p>",
    "Python 3.12 is released in 2025.",
    "NLP is used in AI.",
    "Contact us at info@gmail.com"
]

2. Import the required libraries (re and BeautifulSoup).

In [4]:
import re
from bs4 import BeautifulSoup

3. Convert all text to lowercase.

In [5]:
for text in corpus:
    text = text.lower()
    print(text)

<p>data science is amazing!!! visit https://datascience.com</p>
python 3.12 is released in 2025.
nlp is used in ai.
contact us at info@gmail.com

In [6]:
lowercase_corpus = [text.lower() for text in corpus]

print(lowercase_corpus)

['<p>data science is amazing!!! visit https://datascience.com</p>', 'python 3.12 is released in 2025.', 'nlp is used in ai.', 'contact us at info@gmail.com']

4. Remove HTML tags.

In [7]:
html_removed = [
    BeautifulSoup(text, "html.parser").get_text()
    for text in lowercase_corpus
]

print(html_removed)

['data science is amazing!!! visit https://datascience.com', 'python 3.12 is released in 2025.', 'nlp is used in ai.', 'contact us at info@gmail.com']

5. Remove URLs

In [8]:
url_removed = [
    re.sub(r'https?://\S+|www\.\S+', '', text)
    for text in html_removed
]

print(url_removed)

['data science is amazing!!! visit ', 'python 3.12 is released in 2025.', 'nlp is used in ai.', 'contact us at info@gmail.com']

6. Remove email addresses.

In [9]:
email_removed = [
    re.sub(r'\b[\w\.-]+@[\w\.-]+\.\w+\b', '', text)
    for text in url_removed
]

print(email_removed)

['data science is amazing!!! visit ', 'python 3.12 is released in 2025.', 'nlp is used in ai.', 'contact us at ']

7. Remove digits.

In [10]:
digit_removed = [
    re.sub(r'\d+', '', text)
    for text in email_removed
]

print(digit_removed)

['data science is amazing!!! visit ', 'python . is released in .', 'nlp is used in ai.', 'contact us at ']

8. Remove punctuation and special characters.

In [11]:
punct_removed = [
    re.sub(r'\W+', ' ', text)
    for text in digit_removed
]

print(punct_removed)

['data science is amazing visit ', 'python is released in ', 'nlp is used in ai ', 'contact us at ']

9. Remove extra white spaces.

In [12]:
cleaned_corpus = [
    re.sub(r'\s+', ' ', text).strip()
    for text in punct_removed
]

print(cleaned_corpus)

['data science is amazing visit', 'python is released in', 'nlp is used in ai', 'contact us at']

10. Store the cleaned text in a new list named cleaned_corpus.

In [13]:
print("The cleaned text has been stored in the list 'cleaned_corpus'.")
print(cleaned_corpus)

The cleaned text has been stored in the list 'cleaned_corpus'.
['data science is amazing visit', 'python is released in', 'nlp is used in ai', 'contact us at']

11. Display the original corpus and the cleaned corpus

In [15]:
print("Original Corpus:\n")

for sentence in corpus:
    print(sentence)

print("\nCleaned Corpus:\n")

for sentence in cleaned_corpus:
    print(sentence)

Original Corpus:

<p>Data Science is AMAZING!!! Visit https://datascience.com</p>
Python 3.12 is released in 2025.
NLP is used in AI.
Contact us at info@gmail.com

Cleaned Corpus:

data science is amazing visit
python is released in
nlp is used in ai
contact us at

12. Compare the text before and after cleaning.

In [16]:
print("Comparison Before and After Cleaning\n")

for original, cleaned in zip(corpus, cleaned_corpus):
    print("Original :", original)
    print("Cleaned  :", cleaned)
    print("-" * 60)

Comparison Before and After Cleaning

Original : <p>Data Science is AMAZING!!! Visit https://datascience.com</p>
Cleaned  : data science is amazing visit
------------------------------------------------------------
Original : Python 3.12 is released in 2025.
Cleaned  : python is released in
------------------------------------------------------------
Original : NLP is used in AI.
Cleaned  : nlp is used in ai
------------------------------------------------------------
Original : Contact us at info@gmail.com
Cleaned  : contact us at
------------------------------------------------------------

Post Lab:

Collect five reviews from an online shopping website or social media platform.
Apply the text cleaning techniques learned in this experiment and compare the original and cleaned text.
Write a brief report (100–150 words) explaining the impact of text cleaning on the dataset.

Live Scenario:
An electronics company wants to analyze customer reviews about laptops to improve product design and customer satisfaction. Before applying sentiment analysis or topic modeling, the reviews must be cleaned to remove noise such as HTML tags, URLs, emails, digits, emojis, and punctuation.

Objectives: 

Collect text reviews about laptops.
Apply text cleaning methods (lowercasing, removing HTML tags, URLs, emails, digits, punctuation, extra spaces).
Compare original and cleaned reviews.
Write a short report on the impact of text cleaning.

Sample Dataset

In [17]:
# Sample dataset
reviews = [
    "This Laptop is AMAZING!!! <div>Battery lasts 10 hours</div> Visit https://laptopstore.com",
    "Worst laptop ever… Paid 60000 rupees, stopped working in 3 months!!!",
    "Email me at user123@techhelp.com if you want proof.",
    "Laptop performance is awesome <br> Highly Recommend!!!",
    "Not satisfied :( #slowLaptop"
]

import pandas as pd
df = pd.DataFrame(reviews, columns=['Review'])
df

                                              Review
0  This Laptop is AMAZING!!! <div>Battery lasts 1...
1  Worst laptop ever… Paid 60000 rupees, stopped ...
2  Email me at user123@techhelp.com if you want p...
3  Laptop performance is awesome <br> Highly Reco...
4                       Not satisfied :( #slowLaptop

Import Libraries

In [18]:
import re
import pandas as pd
from bs4 import BeautifulSoup

Clean the Reviews

In [23]:
def clean_text(review):
    review = review.lower()
    review = BeautifulSoup(review, "html.parser").get_text()   # remove HTML tags
    review = re.sub(r"http\S+|www\S+|https\S+", '', review)    # remove URLs
    review = re.sub(r'\S+@\S+', '', review)                    # remove emails
    review = re.sub(r'\d+', '', review)                        # remove digits
    review = re.sub(r'\W+', ' ', review)                       # remove punctuation/special chars
    review = re.sub(r'\s+', ' ', review).strip()               # remove extra spaces
    return review

Compare Before and After

In [20]:
comparison = df[['Review', 'Cleaned_Review']]
comparison

,Review,Cleaned_Review
0,This Laptop is AMAZING!!! <div>Battery lasts 1...,this laptop is amazing battery lasts hours visit
1,"Worst laptop ever… Paid 60000 rupees, stopped ...",worst laptop ever paid rupees stopped working ...
2,Email me at user123@techhelp.com if you want p...,email me at if you want proof
3,Laptop performance is awesome <br> Highly Reco...,laptop performance is awesome highly recommend
4,Not satisfied :( #slowLaptop,not satisfied slowlaptop

Report

Text cleaning greatly improves the quality of customer reviews for NLP tasks. The original dataset contained HTML tags, URLs, email addresses, digits, emojis, and excessive punctuation, which added noise. After cleaning, the text became uniform, lowercase, and free from irrelevant symbols, making it easier to tokenize and analyze. This ensures that algorithms focus only on meaningful words, improving the accuracy of tasks like sentiment analysis and topic modeling. While cleaning removes expressive elements such as emojis or repeated punctuation, the trade‑off is worthwhile because the dataset becomes structured and machine‑readable. Overall, text cleaning enhances data quality and model performance.

Conclusion

Text cleaning transforms messy, unstructured laptop reviews into clean, consistent text. This preprocessing step is essential in NLP pipelines, as it reduces noise, improves model performance, and ensures that the dataset is ready for deeper analysis.